spring:
  datasource:
    pagehelper:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/travel?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root

